export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const SET_QUIZ_RESULTS = "SET_QUIZ_RESULTS";
export const SET_QUIZ_FINISHED = "SET_QUIZ_FINISHED";
export const SET_QUIZ_NEXT = "SET_QUIZ_NEXT";
export const RETRY_QUIZ = "RETRY_QUIZ";
